### ISSUE TITLE
[suggestion] replace USB to UART adapter with USB shield

### ISSUE THREAD

**Issue by eadmaster** [matlo/serialusb#11]
This could make the device acts as a standalone adapter without needing a PC.

reading xinput and DS3 controller inputs should be possible with this lib:
https://github.com/felis/USB_Host_Shield_2.0#xbox-libraries

**Comment by matlo** [comment]
GIMX leverages the input stack of the computer. This choice provides almost 100% compatibility with existing and future input devices.

**Comment by matlo** [comment]
I am not sure if your suggestion is for serialusb or the GIMX adapter.

**Comment by matlo** [comment]
In the first case you still want the USB transfers to be saved on the computer (atmega32u4 chip has a very limited amount of memory).

In the second case, you loose the advantage of using the computer input stack, which provides almost 100% compatibility with existing and future devices.
