### ISSUE TITLE
FYI: Link added to Wireshark Wiki

### ISSUE THREAD

**Issue by hzulla** [matlo/serialusb#4]
Hi there,

thanks for serialusb, which has helped me a lot. But it took me a very long time to actually find it, despite googling various iterations of my problem. To make things easier for others, I have asked to add the following text to the [Wireshark Wiki](https://wiki.wireshark.org/CaptureSetup/USB). Please let me know if you agree with this description of your project.

> MITM hardware with Linux
>
> If the USB host is a black-box device such as a game console and you cannot capture USB traffic on the host's operating system, here are two diy-projects that help you build a simple MITM device to sniff USB messages on the USB cable.
> 
> *SerialUSB* is designed to intercept USB HID traffic. Originally made for the GIMX project (which lets you connect PC game controllers to the PS4 by converting the HID protocol messages). You will need a Linux computer to capture the HID messages and an Arduino-based USB dongle. Parts are cheap. If you don't like soldering, you can buy ready-made "GIMX USB adapters" from the developer and from enthusiasts on eBay and elsewhere. 
> 
> *USBProxy* intercepts USB traffic with a Beaglebone Black, which is reconfigured to act as a USB gadget emulating the device connected to the 2nd USB port. According to the documentation, it allows sniffing non-HID traffic, as well.

**Comment by matlo** [comment]
Hi,

It seems more accurate to say _relay_ and not _intercept_.
Otherwise, the description is good!
