### ISSUE TITLE
Unexpected URB_BULK frames

### ISSUE THREAD

**Issue by dskk** [matlo/serialusb#8]
Hi Matlo,

I recently started to use serialusb and captured packets of SIXAXIS, third-party HID gamepad (HORI: Real Arcade PRO. V3-SA) and simple HID gamepad that I made by myself using at90usb646. 
Then I found out that all of the dumped capture.pcap files countain URB_BULK in/out frames even though none of the gamepads have bulk endpoint.

To check in detail, I ran Wireshark on Windows host PC and captured USB traffics at the same time as serialusb. I used simple self-made HID gamepad having only one interrupt in endpoint.
> gamepad ↔ Linux PC ↔ FT232RL adapter ↔ Arduino Micro↔ Windows PC
(My GIMX DIY USB adapter is made of Arduino Micro + FT232RL)

https://drive.google.com/open?id=1L12dFX3nxMFTKmUe-ekaVx5hCm8y7cgN
https://drive.google.com/open?id=1b_fqd-6W644bnyzoDQsHMB9o-SJwN6nJ
Here I attached links of pcap files.
Windows.pcap seems to be OK, looks identical to those I see when I directly plugged in my gamepad to Windows PC. Also, I confirmed that HID input reports are successfully sent (by Control Panel > Devices and printers > Game Controller Properties).
On the other hand, in Linux.pcap I saw many URB_BULK in/out frames aside from URB_INTERRPUT in frames......
![image](https://user-images.githubusercontent.com/36487148/73607573-1040a000-45fb-11ea-81ed-03e67bd9bad7.png)

Versions:
OS: CentOS 8(1911)
tcpdump: 4.9.2
libusb: 1.0.22

What should I check? If you have any ideas, please let me know.
Thank you in advance.

**Comment by matlo** [comment]
Hi dssk,

The BULK transfers are for device 7, which is very likely the FT232RL.
